name = 'Yue'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'multilangual']
# features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Cyrus Yip'
  homepage = 'https://cyrusyip.org/'
